// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { CreatorsCreateCreatorProfileData, CreatorsCreateCreatorProfileResponse, CreatorsGetMyCreatorProfileResponse, CreatorsUpdateMyCreatorProfileData, CreatorsUpdateMyCreatorProfileResponse, CreatorsGetMyTemplatesData, CreatorsGetMyTemplatesResponse, CreatorsCreateTripTemplateData, CreatorsCreateTripTemplateResponse, CreatorsGetMyTemplateData, CreatorsGetMyTemplateResponse, CreatorsUpdateMyTemplateData, CreatorsUpdateMyTemplateResponse, CreatorsDeleteMyTemplateData, CreatorsDeleteMyTemplateResponse, CreatorsPublishTemplateData, CreatorsPublishTemplateResponse, CreatorsCreateAffiliateLinkData, CreatorsCreateAffiliateLinkResponse, CreatorsGetMyAffiliateLinksData, CreatorsGetMyAffiliateLinksResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, TemplatesDiscoverTemplatesData, TemplatesDiscoverTemplatesResponse, TemplatesGetTemplateData, TemplatesGetTemplateResponse, TemplatesGetTemplateByAffiliateData, TemplatesGetTemplateByAffiliateResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class CreatorsService {
    /**
     * Create Creator Profile
     * Create creator profile for current user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns CreatorPublic Successful Response
     * @throws ApiError
     */
    public static createCreatorProfile(data: CreatorsCreateCreatorProfileData): CancelablePromise<CreatorsCreateCreatorProfileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/creators/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get My Creator Profile
     * Get current user's creator profile.
     * @returns CreatorPublic Successful Response
     * @throws ApiError
     */
    public static getMyCreatorProfile(): CancelablePromise<CreatorsGetMyCreatorProfileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/creators/me'
        });
    }
    
    /**
     * Update My Creator Profile
     * Update current user's creator profile.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns CreatorPublic Successful Response
     * @throws ApiError
     */
    public static updateMyCreatorProfile(data: CreatorsUpdateMyCreatorProfileData): CancelablePromise<CreatorsUpdateMyCreatorProfileResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/creators/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get My Templates
     * Get current creator's templates.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns TripTemplatesPublic Successful Response
     * @throws ApiError
     */
    public static getMyTemplates(data: CreatorsGetMyTemplatesData = {}): CancelablePromise<CreatorsGetMyTemplatesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/creators/templates',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Trip Template
     * Create new trip template.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TripTemplatePublic Successful Response
     * @throws ApiError
     */
    public static createTripTemplate(data: CreatorsCreateTripTemplateData): CancelablePromise<CreatorsCreateTripTemplateResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/creators/templates',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get My Template
     * Get specific template owned by current creator.
     * @param data The data for the request.
     * @param data.templateId
     * @returns TripTemplatePublic Successful Response
     * @throws ApiError
     */
    public static getMyTemplate(data: CreatorsGetMyTemplateData): CancelablePromise<CreatorsGetMyTemplateResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/creators/templates/{template_id}',
            path: {
                template_id: data.templateId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update My Template
     * Update template owned by current creator.
     * @param data The data for the request.
     * @param data.templateId
     * @param data.requestBody
     * @returns TripTemplatePublic Successful Response
     * @throws ApiError
     */
    public static updateMyTemplate(data: CreatorsUpdateMyTemplateData): CancelablePromise<CreatorsUpdateMyTemplateResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/creators/templates/{template_id}',
            path: {
                template_id: data.templateId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete My Template
     * Delete template owned by current creator.
     * @param data The data for the request.
     * @param data.templateId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteMyTemplate(data: CreatorsDeleteMyTemplateData): CancelablePromise<CreatorsDeleteMyTemplateResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/creators/templates/{template_id}',
            path: {
                template_id: data.templateId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Publish Template
     * Publish a draft template.
     * @param data The data for the request.
     * @param data.templateId
     * @returns TripTemplatePublic Successful Response
     * @throws ApiError
     */
    public static publishTemplate(data: CreatorsPublishTemplateData): CancelablePromise<CreatorsPublishTemplateResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/creators/templates/{template_id}/publish',
            path: {
                template_id: data.templateId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Affiliate Link
     * Create affiliate link for published template.
     * @param data The data for the request.
     * @param data.templateId
     * @returns AffiliateLinkPublic Successful Response
     * @throws ApiError
     */
    public static createAffiliateLink(data: CreatorsCreateAffiliateLinkData): CancelablePromise<CreatorsCreateAffiliateLinkResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/creators/templates/{template_id}/affiliate-links',
            path: {
                template_id: data.templateId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get My Affiliate Links
     * Get current creator's affiliate links.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns AffiliateLinksPublic Successful Response
     * @throws ApiError
     */
    public static getMyAffiliateLinks(data: CreatorsGetMyAffiliateLinksData = {}): CancelablePromise<CreatorsGetMyAffiliateLinksResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/creators/affiliate-links',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class TemplatesService {
    /**
     * Discover Templates
     * Discover published trip templates with filtering and search.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.search Search in title and description
     * @param data.category Filter by category
     * @param data.minDuration Minimum duration in days
     * @param data.maxDuration Maximum duration in days
     * @returns TripTemplatesPublic Successful Response
     * @throws ApiError
     */
    public static discoverTemplates(data: TemplatesDiscoverTemplatesData = {}): CancelablePromise<TemplatesDiscoverTemplatesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/templates/discover',
            query: {
                skip: data.skip,
                limit: data.limit,
                search: data.search,
                category: data.category,
                min_duration: data.minDuration,
                max_duration: data.maxDuration
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Template
     * Get specific published template by ID.
     * @param data The data for the request.
     * @param data.templateId
     * @returns TripTemplatePublic Successful Response
     * @throws ApiError
     */
    public static getTemplate(data: TemplatesGetTemplateData): CancelablePromise<TemplatesGetTemplateResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/templates/{template_id}',
            path: {
                template_id: data.templateId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Template By Affiliate
     * Get template via affiliate link and track click.
     * @param data The data for the request.
     * @param data.linkCode
     * @returns TripTemplatePublic Successful Response
     * @throws ApiError
     */
    public static getTemplateByAffiliate(data: TemplatesGetTemplateByAffiliateData): CancelablePromise<TemplatesGetTemplateByAffiliateResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/templates/by-affiliate/{link_code}',
            path: {
                link_code: data.linkCode
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
    
}